export const API = [
    {
        id : 1,
        name : "Albondigas",
        description : "Albondigas veganas",
        details : "Albondigas realizadas de forma 100% artesanal, libre de crueldad animal. Especiales para estofados y guisitos.",
        category: "congelados",
        moodOfSale: "media docena",
        price : 180,
        ingredientes: "Ingredientes: poroto, avena, soja texturizada y especias.",
        stock : 10,
        img : "albondigas.jpg" 
    },
    {
        id : 2,
        name : "Bastoncitos",
        description : "Bastoncitos de acelga",
        details : "Para la realización de estos bastoncitos hemos reinventado la forma en la que nos enseñaron a comer. Para obtener lo que ven en la foto, reutilizamos la penca de la acelca, es decir, lo que usualmente no se come. ¡Y es riquísimo!",
        category: "congelados",
        moodOfSale: "docena",
        price : 140,
        ingredientes: "Ingredientes: acelga, polenta para recubrir, especias.",
        stock : 25,
        img : "bastoncitos.jpg" 
    },
    {
        id : 3,
        name : "Hamburgusa",
        description : "Hamburguesas caseras",
        details : "Hamburguesas 100% caseritas, desde el pan que es riquísimo y blandito hasta la hamburguesa en sí.",
        category: "congelados",
        moodOfSale: "unidad",
        price : 50,
        ingredientes: "Ingredientes : harina integral, lentejas, avena, mix de legumbres, especias.",
        stock : 30,
        img : "hamburguesa.jpg" 
    },
    {
        id : 4,
        name : "Chorivegano",
        description : "Choripan vegano",
        details : "¿Pensaste que nos ibamos a quedar con ganas?, obviaente la respuesta es que no. Nosotros también nos damos el placer de comer un exquisito chori.",
        category: "congelados",
        moodOfSale: 2,
        price : 90,
        ingredientes: "Ingredientes: poroto negro, avena, soja texturizada, vino, especias.",
        stock : 5,
        img : "choripan.jpg" 
    },
    {
        id : 5,
        name : "Focaccias",
        description : "Foccacias caseritas",
        details : "En Lino nos damos algunos gustitos y estas Foccacias si que lo son. Delicioso sabor y de textura suave ahora teneos estos pancitos que te va a volver loco. ¿Que estas esperando?",
        category: "panificados",
        moodOfSale: "unidad",
        price : 110,
        ingredientes: "Ingredientes: poroto negro, avena, soja texturizada, vino, especias.",
        stock : 28,
        img : "foccacias.jpg" 
    },
    {
        id : 6,
        name : "Pizza",
        description : "Pizza vegana",
        details : "Las pizzas veganas son una excelente opción para tener cuando invitamos amigues o nos visita algun familiar. Realmente, no es por agrandarnos pero consideramos que es lo que mejor nos sale. Te aseguramos de que te dejarán muy bien parado.",
        category: "panificados",
        moodOfSale: "unidad",
        price : 130,
        ingredientes: "Ingredientes: harina integral, queso vegano, pimiento, cebolla, aceitunas, especias.",
        stock : 10,
        img : "pizza.jpg" 
    },
    {
        id : 7,
        name : "Milanesas",
        description : "Milanesas veganas",
        details : "Milanesas veganas de todos los colores y sabores. Si estás cansado de comer siempre lo mismo, ahora tenes la posibilidad de comer algo diferente todos los días de la semana. Y escucha, las tenes congeladas, las sacas cuando la plancha este caliente y en 5 minutos tenes tu comida lista. ¿Qué te parece?",
        category: "congelados",
        moodOfSale: 3,
        price : 230,
        ingredientes: "Ingredientes: avena, lenteja, avena, polenta, vegetales, especias.",
        stock : 120,
        img : "milanesas.jpg" 
    },
    {
        id : 8,
        name : "Empanadas",
        description : "Empanadas veganas",
        details : "Y si hablamos de la especialidad de la casa, llego el turno de las empanadas. 100% caseras, desde la masa hasta el relleno. Deliciosas y facilies de cocinar. Otra muy buena opción para quedar bien con tus invitades.",
        category: "congelados",
        moodOfSale: "docena",
        price : 250,
        ingredientes: "Ingredientes: harina integral, soja texturizada, limón, pimiento, tomate, especias.",
        stock : 123,
        img : "empanadas.jpg" 
    },
    {
        id : 9,
        name : "Pan casero",
        description : "Pan casero con relleno",
        details : "Me vas a decir que no se te hace agua la boca cuando ves esta foto. Pan casero y relleno totalmente artesanal. Los realizamos en ocaciones especiales y se van volando. Así que cuando veas que hay en stock no te cuelgues en hablarnos.",
        category: "panificados",
        moodOfSale: "unidad",
        price : 80,
        ingredientes: "Ingredientes: harina integral, semillas, agua, sal, aceite de oliva, especias.",
        stock : 0,
        img : "pan-relleno.jpg" 
    },
    {
        id : 10,
        name : "Tarta casera",
        description : "Tarta casera de diferentes gustos",
        details : "Las tartas son ideales cuando te levantas con mucho hambre, son grandes y te aseguramos que muy rendidoras. Además todos los lunes estamos haciendo y por semana cambiamos los ingredientes. Estate atento a nuestras redes sociales para que veas la de cada semana.",
        category: "panificados",
        moodOfSale: "unidad",
        price : 320,
        ingredientes: "Ingredientes: harina integral, lino, vegetales, especias.",
        stock : 2,
        img : "tarta.jpg" 
    },
    
]